
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://azykvzqesqhnqgwteieh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF6eWt2enFlc3FobnFnd3RlaWVoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE5NDkyOTgsImV4cCI6MjA1NzUyNTI5OH0.u1EAjocWMMpyBYw1slGilujOVr5EYqY4nDZABeicFks";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);

// Enable realtime subscriptions for messages and notifications
const messagesChannel = supabase.channel('public:messages');
messagesChannel
  .on(
    'postgres_changes',
    {
      event: 'INSERT',
      schema: 'public',
      table: 'messages'
    },
    (payload) => {
      console.log('New message received:', payload);
    }
  )
  .subscribe();

const notificationsChannel = supabase.channel('public:notifications');
notificationsChannel
  .on(
    'postgres_changes',
    {
      event: 'INSERT', 
      schema: 'public',
      table: 'notifications'
    },
    (payload) => {
      console.log('New notification received:', payload);
    }
  )
  .subscribe();
